name: 02 Workflow steps

on: 
  workflow_dispatch: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 is running"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 2 is running"



  job-3:
    runs-on: ubuntu-latest
    needs: 
      - job-1
      - job-2
    steps:
      - run: echo "Job 4 is running"

  job-4:
      runs-on: ubuntu-latest
      needs: 
        - job-2
        - job-3
      steps:
        - run: echo "Job 4 is running"
